name: EasyVoteListener
version: 1.4.2
author: bittiez
main: US.bittiez.EasyVoteListener.main
depend: [Votifier]
api-version: 1.15
commands:
    EVL:
        description: EVL Command
        usage: /EVL
permissions:
    EVL.test:
        description: Allows the use /EVL test to test your permissions/rewards
        default: op
    EVL.reload:
        description: Allows the use of /EVL reload to reload the config file
        default: op